### ISSUE TITLE
Table headings not displaying properly 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#94] opened 2018-10-17 01:19 UTC
Reported by Michael:

> Hi all, has anyone looks at lists.ala.org.au lately?  Any non-DwC field is being displayed as something like: [Ljava.lang.Object;@23c88c81, with no data in the column.  The data is there as the facets are working correctly...

**Comment by djtfmartin** [comment] 2018-10-17 11:41
Fixed and deployed

**Comment by nickdos** [comment] 2018-10-30 05:37
Still seeing this @djtfmartin 

![image](https://user-images.githubusercontent.com/532845/47698074-f11dca80-dc61-11e8-9d99-e923fbaf23bd.png)

Version is a SNAPSHOT too - 3.1-SNAPSHOT

**Comment by sat01a** [comment] 2018-10-30 06:41
@djtfmartin, please let me know once this fixed. (It's breaking some of BioCollect web and mobile functionalities)

**Comment by djtfmartin** [comment] 2018-10-30 12:17
it was a regression - caused by updates on 2 different branches.
Fixed now with 3.1 release

**Closed by djtfmartin** 2018-10-30 12:17 UTC
