### ISSUE TITLE
Lists reload Prod removing Authoritative List Flag

### ISSUE THREAD

**Issue by rosemaryjoconnor** [AtlasOfLivingAustralia/specieslist-webapp#248] opened 2023-05-15 00:36 UTC
When reloading an authoritative list in lists.ala.org.au the Authoritative List flag is unset. 
It is not occurring in lists-test.

**Comment by adam-collins** [comment] 2023-06-07 00:39
duplicate of #231

**Closed by adam-collins** 2023-06-07 00:39 UTC
