### ISSUE TITLE
`/ws/speciesListPost` service is generating duplicate `kvp` entries

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#238] opened 2023-02-25 03:40 UTC
Using the `/ws/speciesListPost` service, I'm POST'ing the following JSON (replacing existing list):

```json
{
  "list_items":[
    {
      "itemName":"Abelmoschus ficulneus",
      "kvpValues":[
        {
          "key":"traitName",
          "value":"fire_response"
        },
        {
          "key":"traitValue",
          "value":"fire_killed"
        }
      ]
    },
    {
      "itemName":"Abelmoschus moschatus",
      "kvpValues":[
        {
          "key":"traitName",
          "value":"fire_response"
        },
        {
          "key":"traitValue",
          "value":"resprouts"
        }
      ]
    }
  ]
}
```

The resulting list now shows duplicate entries for the `kvp` data, with `traitName` and `traitValue` appearing twice:

![image](https://user-images.githubusercontent.com/532845/221334283-ff01ec32-92ed-4484-bbab-a93346091f4f.png)

---

**Additional note**: I think the following line needs updating as it only checks if the JSON key `replaceList` is set (`is not null` - not whether it has a `true` or `false` value - the expected behaviour):

https://github.com/AtlasOfLivingAustralia/specieslist-webapp/blob/develop/grails-app/controllers/au/org/ala/specieslist/WebServiceController.groovy#L733

```groovy
if (jsonBody.replaceList != null) {
    replaceList = jsonBody.replaceList
}
```

If a user passes in jSON with `"replaceList": false`, then (I think) it will be evaluated as `true` in the code above (needs testing to confirm), due to it NOT being `null`. It should just be replaced with a "truthy" Groovy check not a null check. This is because `null` is coerced into  `false` during a "truthy" check -- noting that `false` is not the same as `null`.

**Comment by adam-collins** [comment] 2023-06-07 02:31
Made the fix for `replaceList=false`. 

Unable to reproduce the duplication of kvp values. Is this still a problem on lists-test?

**Comment by adam-collins** [comment] 2023-06-14 03:56
Attempting to source a different list that also has the duplicate column issue.

**Comment by adam-collins** [comment] 2023-06-14 06:10
The duplicate column issue was related to old data resources that were reuploaded. It can be fixed manually with SQL `delete k from species_listkvp k left join species_list_item_species_listkvp kvp on k.id = kvp.species_listkvp_id where kvp.species_listkvp_id is null;`

**Comment by adam-collins** [comment] 2023-07-10 05:11
Fixed on production and test

**Closed** 2023-08-02 01:19 UTC
Labels: bug
